//! DNS resolv.conf generation for containers.
//!
//! Reads the host's /etc/resolv.conf, filters it for use inside containers,
//! and handles special cases like systemd-resolved's stub listener.

/// Addresses that only work on the host (systemd-resolved, macOS mDNSResponder).
const LOCAL_STUBS: &[&str] = &["127.0.0.53", "127.0.0.1"];

/// Fallback nameservers when no usable host nameservers are found.
const FALLBACK_NAMESERVERS: &[&str] = &["1.1.1.1", "8.8.8.8"];

/// Generate a resolv.conf suitable for use inside containers.
///
/// Reads the host's /etc/resolv.conf. If all nameservers are localhost
/// stubs (e.g. systemd-resolved's 127.0.0.53), falls back to public DNS.
pub fn generate_resolv_conf() -> String {
    generate_resolv_conf_from(
        std::fs::read_to_string("/etc/resolv.conf").unwrap_or_default(),
    )
}

/// Testable inner function that operates on the content string directly.
fn generate_resolv_conf_from(host_content: String) -> String {
    let mut nameservers = Vec::new();
    let mut other_lines = Vec::new();

    for line in host_content.lines() {
        let trimmed = line.trim();

        if trimmed.starts_with("nameserver") {
            if let Some(addr) = trimmed.split_whitespace().nth(1) {
                if !LOCAL_STUBS.contains(&addr) {
                    nameservers.push(addr.to_string());
                }
            }
        } else if trimmed.starts_with("search") || trimmed.starts_with("options") {
            other_lines.push(trimmed.to_string());
        }
        // Skip comments and empty lines.
    }

    // If no usable nameservers found, use fallback.
    if nameservers.is_empty() {
        nameservers = FALLBACK_NAMESERVERS.iter().map(|s| s.to_string()).collect();
    }

    let mut output = String::new();
    output.push_str("# Generated by rauha\n");
    for ns in &nameservers {
        output.push_str(&format!("nameserver {ns}\n"));
    }
    for line in &other_lines {
        output.push_str(&format!("{line}\n"));
    }

    output
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn preserves_real_nameservers() {
        let host = "\
nameserver 8.8.8.8
nameserver 8.8.4.4
search example.com
";
        let result = generate_resolv_conf_from(host.into());
        assert!(result.contains("nameserver 8.8.8.8"));
        assert!(result.contains("nameserver 8.8.4.4"));
        assert!(result.contains("search example.com"));
    }

    #[test]
    fn replaces_systemd_resolved_stub() {
        let host = "\
# This is /run/systemd/resolve/stub-resolv.conf managed by systemd-resolved
nameserver 127.0.0.53
options edns0 trust-ad
search .
";
        let result = generate_resolv_conf_from(host.into());
        // Should NOT contain 127.0.0.53.
        assert!(!result.contains("127.0.0.53"));
        // Should have fallback nameservers.
        assert!(result.contains("nameserver 1.1.1.1"));
        assert!(result.contains("nameserver 8.8.8.8"));
        // Should preserve options and search.
        assert!(result.contains("options edns0 trust-ad"));
    }

    #[test]
    fn mixed_local_and_real() {
        let host = "\
nameserver 127.0.0.53
nameserver 10.0.0.1
";
        let result = generate_resolv_conf_from(host.into());
        assert!(!result.contains("127.0.0.53"));
        assert!(result.contains("nameserver 10.0.0.1"));
        // Should NOT include fallbacks since we have a real nameserver.
        assert!(!result.contains("1.1.1.1"));
    }

    #[test]
    fn empty_resolv_conf() {
        let result = generate_resolv_conf_from(String::new());
        assert!(result.contains("nameserver 1.1.1.1"));
        assert!(result.contains("nameserver 8.8.8.8"));
    }

    #[test]
    fn localhost_127_0_0_1() {
        let host = "nameserver 127.0.0.1\n";
        let result = generate_resolv_conf_from(host.into());
        assert!(!result.contains("127.0.0.1"));
        assert!(result.contains("nameserver 1.1.1.1"));
    }
}
